export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'
export const CHANGE_HOT_RECOMMENDED = 'CHANGE_HOT_RECOMMENDED'
export const CHANGE_NEW_ALBUM = 'CHANGE_NEW_ALBUM'
export const CHANGE_TOP_LIST = 'CHANGE_TOP_LIST'
export const CHANGE_UP_RANKING = 'CHANGE_